export const TOKENS = {
  AuthService: Symbol('AuthService'),
  CampaignCounterRepository: Symbol('CampaignCounterRepository'),
  CampaignRepository: Symbol('CampaignRepository'),
  CampaignService: Symbol('CampaignService'),
  ContactRepository: Symbol('ContactRepository'),
  CrmEntityRepository: Symbol('CrmEntityRepository'),
  CrmService: Symbol('CrmService'),
  GeocodingService: Symbol('GeocodingService'),
  InventoryCounterRepository: Symbol('InventoryCounterRepository'),
  InventoryRepository: Symbol('InventoryRepository'),
  InventoryService: Symbol('InventoryService'),
  UploadService: Symbol('UploadService'),
  UserRepository: Symbol('UserRepository'),
  UserService: Symbol('UserService'),
};
