import { useEffect, useState } from 'react';

import {
  downloadDocument,
  generatePlanDocument,
  getPlanDocuments,
} from '../../api/documentApi';
import type { DocumentType, PlanDocument } from '../../types/document';

const documentLabels: Record<DocumentType, string> = {
  PlanProposal: 'Plan Proposal PDF',
  Quotation: 'Quotation PDF',
  InternalCostSheet: 'Internal Cost Sheet',
};

const DocumentPanel = ({
  planId,
  beforeGenerate,
}: {
  planId: string;
  beforeGenerate: () => Promise<boolean>;
}) => {
  const [documents, setDocuments] = useState<PlanDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<DocumentType | null>(null);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true);
    try {
      setDocuments(await getPlanDocuments(planId));
      setError('');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load documents');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
  }, [planId]);

  const generate = async (documentType: DocumentType) => {
    setGenerating(documentType);
    setError('');
    try {
      if (!(await beforeGenerate())) return;
      const document = await generatePlanDocument(planId, documentType);
      setDocuments((current) => [document, ...current]);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate document');
    } finally {
      setGenerating(null);
    }
  };

  return (
    <section className="rounded-lg border border-slate-200 bg-white p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h3 className="font-semibold text-slate-900">Documents</h3>
          <p className="mt-1 text-xs text-slate-500">
            Generate version-specific PDFs from the latest saved plan data.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {(Object.keys(documentLabels) as DocumentType[]).map((type) => (
            <button
              key={type}
              type="button"
              disabled={generating !== null}
              onClick={() => void generate(type)}
              className={type === 'InternalCostSheet' ? warningButton : secondaryButton}
            >
              {generating === type ? 'Generating...' : `Generate ${documentLabels[type]}`}
            </button>
          ))}
        </div>
      </div>

      <p className="mt-3 text-xs font-medium text-amber-700">
        Internal Cost Sheet is internal only and contains cost and margin.
      </p>
      {error ? <p className="mt-3 text-sm text-red-600">{error}</p> : null}

      <div className="mt-4 overflow-x-auto">
        <table className="w-full min-w-[620px] text-left text-sm">
          <thead className="bg-slate-50 text-slate-500">
            <tr>
              <th className="px-3 py-2 font-medium">Type</th>
              <th className="px-3 py-2 font-medium">Generated</th>
              <th className="px-3 py-2 font-medium">Generated By</th>
              <th className="px-3 py-2 text-right font-medium">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {documents.map((document) => (
              <tr key={document.id}>
                <td className="px-3 py-3 font-medium">{documentLabels[document.documentType]}</td>
                <td className="px-3 py-3 text-slate-600">{formatDateTime(document.generatedAt)}</td>
                <td className="px-3 py-3 text-slate-600">
                  {document.generatedBy?.name || document.generatedBy?.email || '-'}
                </td>
                <td className="px-3 py-3 text-right">
                  <button
                    type="button"
                    onClick={() => void downloadDocument(document).catch((err) => setError(err.message))}
                    className={linkButton}
                  >
                    Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {loading ? <p className="p-4 text-center text-sm text-slate-500">Loading documents...</p> : null}
        {!loading && !documents.length ? (
          <p className="p-4 text-center text-sm text-slate-500">No documents generated yet.</p>
        ) : null}
      </div>
    </section>
  );
};

const formatDateTime = (value: string) =>
  new Intl.DateTimeFormat('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(value));

const secondaryButton =
  'rounded-md border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50';
const warningButton =
  'rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-medium text-amber-800 hover:bg-amber-100 disabled:opacity-50';
const linkButton = 'text-sm font-medium text-emerald-700 hover:text-emerald-900';

export default DocumentPanel;
